name = "bcl-portal"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".cloudflare_build"

[build]
command = "npm run pages:build"

[vars]
# NEXT_PUBLIC_SUPABASE_URL = "your-project-url"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
