// =============================================================================
// Widget Registry – Default System Widgets
// =============================================================================
import { WidgetDefinition } from '@/types/widget';

export const defaultWidgetRegistry: WidgetDefinition[] = [
    {
        id: 'members',
        title: '회원 관리',
        description: '총 회원 수, 활성/만료 현황, 신규 가입 추적 및 빠른 회원 등록',
        category: 'finance',
        icon: 'IconMembers',
        iconColor: '#3B82F6',
        badgeKey: 'members_today_new',
        heroMetric: {
            queryKey: 'members_active_count',
            format: 'fraction',
            denominatorKey: 'members_total_count',
        },
        contextItems: [
            { label: '오늘 신규', queryKey: 'members_today_new', format: 'number' },
            { label: '만료 임박 (7일)', queryKey: 'members_expiring_soon', format: 'number', alertThreshold: 3 },
        ],
        progressBar: { valueKey: 'members_active_count', maxKey: 'members_total_count', color: '#3B82F6' },
        actions: [
            { label: '+ 회원 등록', type: 'modal', modalId: 'quick-add-member', group: 'primary', icon: 'IconPlus', description: '새로운 회원을 빠르게 등록합니다' },
            { label: '회원 검색', type: 'modal', modalId: 'quick-search-member', group: 'primary', icon: 'IconSearch', description: '이름/전화번호로 회원을 검색합니다' },
            { label: '만료 임박 회원', type: 'link', href: '/admin/members?filter=expiring', group: 'secondary', icon: 'IconAlert', description: '7일 이내 멤버십 만료 예정 회원 목록' },
            { label: '전체 목록 →', type: 'link', href: '/admin/members', group: 'link' },
        ],
        miniList: null,
        defaultEnabled: true,
        defaultOrder: 1,
    },
    {
        id: 'schedule',
        title: '수업 스케줄',
        description: '오늘 수업 현황, 다음 수업 정보, 예약률 확인 및 빠른 수업 등록',
        category: 'operations',
        icon: 'IconCalendar',
        iconColor: '#F59E0B',
        badgeKey: 'schedule_remaining_today',
        heroMetric: { queryKey: 'schedule_remaining_today', format: 'number' },
        contextItems: [
            { label: '다음 수업', queryKey: 'schedule_next_session_time', format: 'time' },
            { label: '오늘 평균 예약률', queryKey: 'schedule_avg_booking_rate', format: 'number' },
            { label: '오늘 총 수업', queryKey: 'schedule_total_today', format: 'number' },
        ],
        progressBar: null,
        actions: [
            { label: '+ 수업 추가', type: 'modal', modalId: 'quick-add-session', group: 'primary', icon: 'IconPlus', description: '새 수업을 빠르게 등록합니다' },
            { label: '수업 취소', type: 'modal', modalId: 'quick-cancel-session', group: 'secondary', icon: 'IconClose', description: '오늘 수업을 취소하고 예약자에게 알림' },
            { label: '코치 변경', type: 'modal', modalId: 'quick-change-coach', group: 'secondary', icon: 'IconSwap', description: '오늘 수업의 담당 코치를 변경합니다' },
            { label: '오늘 스케줄 →', type: 'link', href: '/admin/operations/schedule', group: 'link' },
            { label: '예약 현황 →', type: 'link', href: '/admin/operations/reservations', group: 'link' },
        ],
        miniList: { queryKey: 'schedule_upcoming_sessions', maxItems: 2, itemFormat: { primary: 'start_time', secondary: 'coach_name', timestamp: 'start_time' } },
        defaultEnabled: true,
        defaultOrder: 2,
    },
    {
        id: 'checkins',
        title: '체크인',
        description: '오늘 체크인 현황, 실시간 입장 기록, 수동 체크인 처리',
        category: 'operations',
        icon: 'IconFaceId',
        iconColor: '#22C55E',
        badgeKey: null,
        heroMetric: { queryKey: 'checkins_today_count', format: 'number' },
        contextItems: [
            { label: 'QR 체크인', queryKey: 'checkins_today_qr', format: 'number' },
            { label: '키오스크', queryKey: 'checkins_today_kiosk', format: 'number' },
            { label: '수동 처리', queryKey: 'checkins_today_manual', format: 'number' },
        ],
        progressBar: null,
        actions: [
            { label: '수동 체크인', type: 'modal', modalId: 'quick-manual-checkin', group: 'primary', icon: 'IconHand', description: 'QR 미지참/단말기 오류 시 수동 체크인' },
            { label: '체크인 취소', type: 'modal', modalId: 'quick-cancel-checkin', group: 'secondary', icon: 'IconUndo', description: '잘못된 체크인 기록을 취소합니다' },
            { label: '전체 로그 →', type: 'link', href: '/admin/checkins', group: 'link' },
        ],
        miniList: { queryKey: 'checkins_recent', maxItems: 3, itemFormat: { primary: 'member_name', secondary: 'checkin_method', timestamp: 'checkin_time' } },
        defaultEnabled: true,
        defaultOrder: 3,
    },
    {
        id: 'transactions',
        title: '결제 내역',
        description: '오늘 결제 현황, 미확인 결제 건수, 수동 결제 등록',
        category: 'finance',
        icon: 'IconDollar',
        iconColor: '#8B5CF6',
        badgeKey: 'transactions_pending_count',
        heroMetric: { queryKey: 'transactions_today_total', format: 'currency', currencySymbol: '₩' },
        contextItems: [
            { label: '오늘 결제 건수', queryKey: 'transactions_today_count', format: 'number' },
            { label: '미확인 건', queryKey: 'transactions_pending_count', format: 'number', alertThreshold: 1 },
            { label: '이번 달 누적', queryKey: 'transactions_month_total', format: 'currency' },
        ],
        progressBar: null,
        actions: [
            { label: '+ 수동 결제', type: 'modal', modalId: 'quick-add-transaction', group: 'primary', icon: 'IconPlus', description: '현금/계좌이체 등 수동 결제를 등록합니다' },
            { label: '환불 처리', type: 'modal', modalId: 'quick-refund', group: 'primary', icon: 'IconRefund', description: '결제 건에 대한 환불을 처리합니다' },
            { label: '미확인 결제', type: 'link', href: '/admin/transactions?status=pending', group: 'secondary', icon: 'IconAlert', description: '확인 대기 중인 결제 건 목록' },
            { label: '전체 내역 →', type: 'link', href: '/admin/transactions', group: 'link' },
            { label: '월간 정산 →', type: 'link', href: '/admin/insights/finance', group: 'link' },
        ],
        miniList: { queryKey: 'transactions_recent', maxItems: 2, itemFormat: { primary: 'member_name', secondary: 'amount', timestamp: 'created_at' } },
        defaultEnabled: true,
        defaultOrder: 4,
    },
    {
        id: 'notifications',
        title: '알림 센터',
        description: '발송 현황, 미읽음 알림 추적, 빠른 알림 전송',
        category: 'crm',
        icon: 'IconMegaphone',
        iconColor: '#EC4899',
        badgeKey: 'notifications_unread_count',
        heroMetric: { queryKey: 'notifications_unread_count', format: 'number' },
        contextItems: [
            { label: '오늘 발송', queryKey: 'notifications_today_sent', format: 'number' },
            { label: '미읽음', queryKey: 'notifications_unread_count', format: 'number', alertThreshold: 5 },
            { label: '예약 발송 대기', queryKey: 'notifications_scheduled_count', format: 'number' },
        ],
        progressBar: null,
        actions: [
            { label: '빠른 알림 전송', type: 'modal', modalId: 'quick-send-notification', group: 'primary', icon: 'IconMegaphone', description: '전체 또는 특정 그룹에게 알림 발송' },
            { label: '예약 알림 등록', type: 'modal', modalId: 'quick-schedule-notification', group: 'secondary', icon: 'IconClock', description: '특정 시간에 자동으로 발송할 알림 예약' },
            { label: '수업 안내 발송', type: 'modal', modalId: 'quick-class-reminder', group: 'secondary', icon: 'IconCalendar', description: '오늘 수업 예약자에게 안내 알림 발송' },
            { label: '알림 센터 →', type: 'link', href: '/admin/crm/notifications', group: 'link' },
        ],
        miniList: null,
        defaultEnabled: true,
        defaultOrder: 5,
    },
    {
        id: 'memberships',
        title: '멤버십 현황',
        description: '활성 멤버십, 만료 임박 회원, 인기 요금제 파악',
        category: 'finance',
        icon: 'IconCreditCard',
        iconColor: '#06B6D4',
        badgeKey: 'memberships_expiring_7days',
        heroMetric: { queryKey: 'memberships_active_count', format: 'number' },
        contextItems: [
            { label: '활성 멤버십', queryKey: 'memberships_active_count', format: 'number' },
            { label: '7일 내 만료', queryKey: 'memberships_expiring_7days', format: 'number', alertThreshold: 3 },
            { label: '인기 요금제', queryKey: 'memberships_popular_plan', format: 'text' },
        ],
        progressBar: null,
        actions: [
            { label: '+ 멤버십 부여', type: 'modal', modalId: 'quick-assign-membership', group: 'primary', icon: 'IconPlus', description: '회원에게 멤버십을 직접 부여합니다' },
            { label: '일시정지 처리', type: 'modal', modalId: 'quick-pause-membership', group: 'secondary', icon: 'IconPause', description: '멤버십을 일시정지(홀딩) 처리합니다' },
            { label: '만료 연장', type: 'modal', modalId: 'quick-extend-membership', group: 'secondary', icon: 'IconExtend', description: '멤버십 기간을 수동으로 연장합니다' },
            { label: '만료 임박 →', type: 'link', href: '/admin/memberships?filter=expiring', group: 'link' },
            { label: '요금제 관리 →', type: 'link', href: '/admin/plans', group: 'link' },
        ],
        miniList: null,
        defaultEnabled: true,
        defaultOrder: 6,
    },
    {
        id: 'coaches',
        title: '코치 현황',
        description: '활동 코치 수, 오늘 배정 현황, 미배정 수업 추적',
        category: 'operations',
        icon: 'IconSettings',
        iconColor: '#F97316',
        badgeKey: 'coaches_unassigned_sessions',
        heroMetric: { queryKey: 'coaches_active_count', format: 'number' },
        contextItems: [
            { label: '오늘 배정 코치', queryKey: 'coaches_assigned_today', format: 'number' },
            { label: '미배정 수업', queryKey: 'coaches_unassigned_sessions', format: 'number', alertThreshold: 1 },
        ],
        progressBar: { valueKey: 'coaches_assigned_today', maxKey: 'coaches_active_count', color: '#F97316' },
        actions: [
            { label: '+ 코치 등록', type: 'modal', modalId: 'quick-add-coach', group: 'primary', icon: 'IconPlus', description: '새로운 코치를 등록합니다' },
            { label: '수업 배정', type: 'modal', modalId: 'quick-assign-coach', group: 'primary', icon: 'IconCalendar', description: '미배정 수업에 코치를 배정합니다' },
            { label: '코치 관리 →', type: 'link', href: '/admin/operations/coaches', group: 'link' },
            { label: '성과 분석 →', type: 'link', href: '/admin/insights/coaches', group: 'link' },
        ],
        miniList: null,
        defaultEnabled: true,
        defaultOrder: 7,
    },
    {
        id: 'support',
        title: '고객 문의',
        description: '미처리 티켓, 오늘 접수 문의, 긴급 문의 추적',
        category: 'crm',
        icon: 'IconHand',
        iconColor: '#EF4444',
        badgeKey: 'support_pending_count',
        heroMetric: { queryKey: 'support_pending_count', format: 'number' },
        contextItems: [
            { label: '미처리 문의', queryKey: 'support_pending_count', format: 'number', alertThreshold: 1 },
            { label: '오늘 접수', queryKey: 'support_today_count', format: 'number' },
            { label: '긴급', queryKey: 'support_urgent_count', format: 'number', alertThreshold: 1 },
        ],
        progressBar: null,
        actions: [
            { label: '빠른 답변', type: 'modal', modalId: 'quick-reply-ticket', group: 'primary', icon: 'IconReply', description: '대기 중인 최우선 문의에 바로 답변합니다' },
            { label: '대기 문의 →', type: 'link', href: '/admin/crm/support?status=pending', group: 'link' },
            { label: '피드백 →', type: 'link', href: '/admin/crm/feedback', group: 'link' },
        ],
        miniList: { queryKey: 'support_recent_tickets', maxItems: 2, itemFormat: { primary: 'subject', secondary: 'member_name', timestamp: 'created_at' } },
        defaultEnabled: true,
        defaultOrder: 8,
    },
];
