-- ============================================================================
-- BCL Portal — 20260709140000_seed_movement_library.sql
-- 운동 라이브러리 시드 — 아카이브(docs-legacy/docs/planning/wod_exercise_list.md) 167종.
--   category=movement_categories.slug FK · slug 자동생성(충돌 0) · difficulty ★→1..5
--   equipment/primary_muscles 배열 분리 · source_tag='wod_exercise_list' · 멱등(ON CONFLICT slug).
-- ============================================================================
INSERT INTO public.movement_library (slug,name_ko,name_en,category,equipment,difficulty_level,primary_muscles,coaching_points,source_tag,is_active) VALUES
('clean-and-jerk','클린 앤 저크','Clean & Jerk','weightlifting',ARRAY['바벨'],5,ARRAY['전신','대퇴사두','삼각근','승모근'],'1st pull→catch→jerk 3단계. 바를 몸에 붙여 당기고 elbows high','wod_exercise_list',true),
('snatch','스내치','Snatch','weightlifting',ARRAY['바벨'],5,ARRAY['전신','광배근','대퇴사두','삼각근'],'광폭 그립, 바를 최대한 몸 가까이. 머리 위 고정 시 어깨 활성화','wod_exercise_list',true),
('power-clean','파워 클린','Power Clean','weightlifting',ARRAY['바벨'],4,ARRAY['전신','햄스트링','삼각근','승모근'],'스쿼트 없이 수직점프 후 캐치. 엘보우 앞으로 빠르게','wod_exercise_list',true),
('power-snatch','파워 스내치','Power Snatch','weightlifting',ARRAY['바벨'],4,ARRAY['전신','광배근','삼각근'],'하프 스쿼트 이하로 캐치. 오버헤드 안정성 필수','wod_exercise_list',true),
('hang-clean','행 클린','Hang Clean','weightlifting',ARRAY['바벨'],3,ARRAY['햄스트링','둔근','승모근'],'무릎 위에서 시작. 힙 히지 강조, 2nd pull 타이밍','wod_exercise_list',true),
('hang-power-clean','행 파워 클린','Hang Power Clean','weightlifting',ARRAY['바벨'],3,ARRAY['햄스트링','둔근','승모근'],'행 클린과 동일하나 스쿼트 없이 캐치','wod_exercise_list',true),
('hang-snatch','행 스내치','Hang Snatch','weightlifting',ARRAY['바벨'],4,ARRAY['전신','광배근','삼각근'],'무릎 위 시작, 힙 익스텐션 후 풀 언더','wod_exercise_list',true),
('clean-pull','클린 풀','Clean Pull','weightlifting',ARRAY['바벨'],3,ARRAY['햄스트링','광배근','승모근'],'캐치 없이 최대 높이까지 당기기. 트리플 익스텐션 연습','wod_exercise_list',true),
('snatch-pull','스내치 풀','Snatch Pull','weightlifting',ARRAY['바벨'],3,ARRAY['햄스트링','광배근','승모근'],'광폭 그립으로 클린 풀과 동일 개념','wod_exercise_list',true),
('deadlift','데드리프트','Deadlift','weightlifting',ARRAY['바벨'],2,ARRAY['햄스트링','둔근','척추기립근','광배근'],'중립 척추 유지, 바를 몸 가까이. 발뒤꿈치로 밀어내는 느낌','wod_exercise_list',true),
('romanian-deadlift','루마니안 데드리프트','Romanian Deadlift','weightlifting',ARRAY['바벨'],2,ARRAY['햄스트링','둔근'],'무릎 미세하게 굽히고 힙 힌지. 햄스트링 스트레치 느낌','wod_exercise_list',true),
('sumo-deadlift','수모 데드리프트','Sumo Deadlift','weightlifting',ARRAY['바벨'],2,ARRAY['내전근','둔근','햄스트링'],'발 넓게 벌리고 그립 발 안쪽. 무릎 발 방향 정렬','wod_exercise_list',true),
('sumo-deadlift-high-pull','수모 데드리프트 하이풀','Sumo Deadlift High Pull','weightlifting',ARRAY['바벨','케틀벨'],3,ARRAY['전신','삼각근','승모근'],'풀 후 팔꿈치 높이 올리기. CrossFit 기초 동작 중 하나','wod_exercise_list',true),
('back-squat','백 스쿼트','Back Squat','weightlifting',ARRAY['바벨','랙'],2,ARRAY['대퇴사두','둔근','햄스트링'],'바 위치는 high bar 또는 low bar. 깊이는 평행 이하','wod_exercise_list',true),
('front-squat','프론트 스쿼트','Front Squat','weightlifting',ARRAY['바벨','랙'],3,ARRAY['대퇴사두','코어','삼각근'],'클린 그립 또는 크로스 그립. 엘보우 높게 유지','wod_exercise_list',true),
('overhead-squat','오버헤드 스쿼트','Overhead Squat','weightlifting',ARRAY['바벨'],4,ARRAY['전신','삼각근','코어','대퇴사두'],'광폭 그립, 바를 귀 뒤에 위치. 코어와 어깨 안정성 핵심','wod_exercise_list',true),
('strict-press','스트릭트 프레스','Strict Press','weightlifting',ARRAY['바벨'],2,ARRAY['삼각근','삼두근','코어'],'힙 무브먼트 없이 수직 프레스. 코어 긴장 유지','wod_exercise_list',true),
('push-press','푸시 프레스','Push Press','weightlifting',ARRAY['바벨'],2,ARRAY['삼각근','대퇴사두','삼두근'],'딥 앤 드라이브로 모멘텀 생성 후 프레스. 락아웃 완전히','wod_exercise_list',true),
('push-jerk','푸시 저크','Push Jerk','weightlifting',ARRAY['바벨'],3,ARRAY['삼각근','대퇴사두','코어'],'딥 후 바를 올리며 동시에 아래로 드롭. 스플릿 없이','wod_exercise_list',true),
('split-jerk','스플릿 저크','Split Jerk','weightlifting',ARRAY['바벨'],4,ARRAY['삼각근','대퇴사두','코어'],'저크 후 스플릿 스탠스로 착지. 앞발 뒤꿈치-뒷발 볼 착지','wod_exercise_list',true),
('thruster','스러스터','Thruster','weightlifting',ARRAY['바벨','덤벨'],3,ARRAY['전신','대퇴사두','삼각근'],'프론트 스쿼트 + 푸시 프레스 연속 동작. Fran의 핵심','wod_exercise_list',true),
('barbell-row','바벨 로우','Barbell Row','weightlifting',ARRAY['바벨'],2,ARRAY['광배근','승모근','이두근'],'힙 힌지 후 바를 복부로 당기기. 팔꿈치 몸통 가까이','wod_exercise_list',true),
('good-morning','굿모닝','Good Morning','weightlifting',ARRAY['바벨'],3,ARRAY['햄스트링','척추기립근','둔근'],'무릎 약간 굽히고 힙 힌지. 척추 중립 절대 유지','wod_exercise_list',true),
('jerk-balance','저크 발란스','Jerk Balance','weightlifting',ARRAY['바벨'],3,ARRAY['삼각근','코어','대퇴사두'],'스플릿 저크 전 단계 연습. 스플릿 위치 체득','wod_exercise_list',true),
('snatch-balance','스내치 밸런스','Snatch Balance','weightlifting',ARRAY['바벨'],4,ARRAY['전신','삼각근','코어'],'백 스쿼트 자세에서 오버헤드로 드롭. 언더 스피드 훈련','wod_exercise_list',true),
('clean-and-jerk-complex','클린 앤 저크 콤플렉스','Clean & Jerk Complex','weightlifting',ARRAY['바벨'],5,ARRAY['전신'],'클린 + 저크를 다양한 조합으로 묶어서. 볼륨 훈련','wod_exercise_list',true),
('strict-pull-up','풀업 (스트릭트)','Strict Pull-up','gymnastics',ARRAY['풀업바'],3,ARRAY['광배근','이두근','코어'],'데드행에서 턱이 바 위로. 스윙 없이 순수 근력','wod_exercise_list',true),
('kipping-pull-up','풀업 (키핑)','Kipping Pull-up','gymnastics',ARRAY['풀업바'],3,ARRAY['광배근','코어','어깨'],'스윙 모멘텀 활용. hollow→arch→pull. 스트릭트 선행 권장','wod_exercise_list',true),
('butterfly-pull-up','풀업 (버터플라이)','Butterfly Pull-up','gymnastics',ARRAY['풀업바'],4,ARRAY['광배근','코어','어깨'],'순환 스윙 패턴. 고효율 연속 동작. 타이밍이 핵심','wod_exercise_list',true),
('chest-to-bar-pull-up','체스트 투 바 풀업','Chest-to-Bar Pull-up','gymnastics',ARRAY['풀업바'],4,ARRAY['광배근','이두근','코어'],'가슴이 바에 닿아야 유효. 더 높은 풀 요구','wod_exercise_list',true),
('ring-muscle-up','링 머슬업','Ring Muscle-up','gymnastics',ARRAY['링'],5,ARRAY['광배근','삼두근','가슴','코어'],'키핑 풀 후 딥으로 전환. 거짓 그립(false grip) 활용','wod_exercise_list',true),
('bar-muscle-up','바 머슬업','Bar Muscle-up','gymnastics',ARRAY['풀업바'],5,ARRAY['광배근','삼두근','코어'],'바 위로 몸을 넘기는 전환이 핵심. hips to bar 먼저','wod_exercise_list',true),
('strict-hspu','핸드스탠드 푸시업 (스트릭트)','Strict HSPU','gymnastics',ARRAY['벽'],4,ARRAY['삼각근','삼두근','상부승모근'],'벽에 기대어 물구나무. 헤드 터치 후 완전 락아웃','wod_exercise_list',true),
('kipping-hspu','핸드스탠드 푸시업 (키핑)','Kipping HSPU','gymnastics',ARRAY['벽'],4,ARRAY['삼각근','삼두근','코어'],'다리 킥 모멘텀 활용. 표준은 헤드 to 앱맷','wod_exercise_list',true),
('handstand-walk','핸드스탠드 워크','Handstand Walk','gymnastics',ARRAY[]::text[],5,ARRAY['삼각근','코어','손목'],'어깨 위에 힙 위에 발 정렬. 손가락으로 밸런스 조절','wod_exercise_list',true),
('ring-dip','링 딥','Ring Dip','gymnastics',ARRAY['링'],3,ARRAY['삼두근','가슴','삼각근'],'링 안정화가 어려움. 링을 몸 쪽으로 모아서','wod_exercise_list',true),
('bar-dip','바 딥','Bar Dip','gymnastics',ARRAY['평행봉','딥스바'],2,ARRAY['삼두근','가슴','삼각근'],'팔꿈치 너무 벌어지지 않게. 완전 락아웃','wod_exercise_list',true),
('toes-to-bar','토스 투 바','Toes-to-Bar','gymnastics',ARRAY['풀업바'],3,ARRAY['복근','고관절굴곡근','광배근'],'발끝이 바에 터치. hollow→arch 사이클 활용','wod_exercise_list',true),
('knees-to-elbow','니즈 투 엘보우','Knees-to-Elbow','gymnastics',ARRAY['풀업바'],2,ARRAY['복근','고관절굴곡근'],'T2B 보다 낮은 단계. 무릎이 팔꿈치에 닿아야','wod_exercise_list',true),
('knees-to-chest','니즈 투 체스트','Knees-to-Chest','gymnastics',ARRAY['풀업바'],1,ARRAY['복근','고관절굴곡근'],'가장 기본 행잉 코어. 무릎을 가슴으로','wod_exercise_list',true),
('air-squat','에어 스쿼트','Air Squat','gymnastics',ARRAY[]::text[],1,ARRAY['대퇴사두','둔근','햄스트링'],'힙이 무릎 아래로. 가슴 올리고 무릎 발 방향','wod_exercise_list',true),
('pistol-squat','피스톨 스쿼트','Pistol Squat','gymnastics',ARRAY[]::text[],4,ARRAY['대퇴사두','둔근','코어'],'외발 풀 스쿼트. 밸런스와 유연성 모두 필요','wod_exercise_list',true),
('box-jump','박스 점프','Box Jump','gymnastics',ARRAY['박스'],2,ARRAY['대퇴사두','둔근','종아리'],'두발 착지, 완전히 서서 립오버. 내려올 때 조심','wod_exercise_list',true),
('box-jump-over','박스 점프 오버','Box Jump Over','gymnastics',ARRAY['박스'],2,ARRAY['대퇴사두','둔근','종아리'],'박스를 넘어서 반대편 착지','wod_exercise_list',true),
('step-up','스텝업','Step-up','gymnastics',ARRAY['박스'],1,ARRAY['대퇴사두','둔근'],'한발씩 박스 위로. 무릎 부상 있을 때 대안','wod_exercise_list',true),
('burpee','버피','Burpee','gymnastics',ARRAY[]::text[],2,ARRAY['전신'],'플랭크 내려갔다 점프. 손 머리 위에서 박수 또는 클랩','wod_exercise_list',true),
('bar-facing-burpee','바 페이싱 버피','Bar-facing Burpee','gymnastics',ARRAY['바벨'],2,ARRAY['전신'],'버피 후 바벨 양발 점프 오버','wod_exercise_list',true),
('burpee-box-jump-over','버피 박스 점프오버','Burpee Box Jump Over','gymnastics',ARRAY['박스'],3,ARRAY['전신'],'버피 후 박스 점프 오버 연속','wod_exercise_list',true),
('push-up','푸시업','Push-up','gymnastics',ARRAY[]::text[],1,ARRAY['가슴','삼두근','삼각근'],'척추 일직선. 가슴이 바닥에 닿고 완전 락아웃','wod_exercise_list',true),
('ring-push-up','링 푸시업','Ring Push-up','gymnastics',ARRAY['링'],2,ARRAY['가슴','삼두근','코어'],'불안정 서피스로 난이도 상승. 링을 내전','wod_exercise_list',true),
('sit-up','싯업','Sit-up','gymnastics',ARRAY[]::text[],1,ARRAY['복근','고관절굴곡근'],'발 고정하고 어깨가 발뒤꿈치 넘어서. 완전 가동범위','wod_exercise_list',true),
('ghd-sit-up','GHD 싯업','GHD Sit-up','gymnastics',ARRAY['GHD머신'],3,ARRAY['복근','고관절굴곡근'],'과신전 후 완전 굴곡. 처음엔 ROM 제한 권장','wod_exercise_list',true),
('ghd-hip-extension','GHD 힙 익스텐션','GHD Hip Extension','gymnastics',ARRAY['GHD머신'],2,ARRAY['햄스트링','둔근','척추기립근'],'수평에서 힙이 패드 위 오도록','wod_exercise_list',true),
('back-extension','백 익스텐션','Back Extension','gymnastics',ARRAY['GHD','하이퍼익스텐션'],2,ARRAY['척추기립근','둔근','햄스트링'],'상체를 수평으로 내렸다 수직으로 올리기','wod_exercise_list',true),
('rope-climb','로프 클라임 (레그스)','Rope Climb','gymnastics',ARRAY['로프'],3,ARRAY['광배근','이두근','코어'],'J-hook 또는 S-wrap 발 기술. 팔보다 다리 활용','wod_exercise_list',true),
('legless-rope-climb','레그리스 로프 클라임','Legless Rope Climb','gymnastics',ARRAY['로프'],5,ARRAY['광배근','이두근','코어'],'다리 사용 없이 팔만으로. 극상 난이도','wod_exercise_list',true),
('l-sit','L-싯','L-sit','gymnastics',ARRAY['평행봉','박스','링'],3,ARRAY['복근','고관절굴곡근','삼두근'],'팔 완전 신전, 다리 수평 유지. 시간 또는 거리','wod_exercise_list',true),
('handstand-hold','핸드스탠드 홀드','Handstand Hold','gymnastics',ARRAY['벽'],3,ARRAY['삼각근','코어','손목'],'벽 지지 또는 프리스탠딩. 몸 일직선','wod_exercise_list',true),
('walking-lunge','워킹 런지','Walking Lunge','gymnastics',ARRAY['바벨','덤벨'],2,ARRAY['대퇴사두','둔근','햄스트링'],'무릎이 바닥에 닿고 앞발 90도. 상체 직립','wod_exercise_list',true),
('reverse-lunge','리버스 런지','Reverse Lunge','gymnastics',ARRAY[]::text[],2,ARRAY['대퇴사두','둔근'],'뒤로 내딛기. 앞 무릎 과전진 방지','wod_exercise_list',true),
('broad-jump','브로드 점프','Broad Jump','gymnastics',ARRAY[]::text[],2,ARRAY['대퇴사두','둔근','종아리'],'수평 거리 최대화 점프. 착지 안정성','wod_exercise_list',true),
('ring-row','링 로우','Ring Row','gymnastics',ARRAY['링'],2,ARRAY['광배근','이두근','코어'],'몸 기울기로 난이도 조절. 가슴이 링에','wod_exercise_list',true),
('feet-elevated-ring-row','발 올린 링 로우','Feet-elevated Ring Row','gymnastics',ARRAY['링','박스'],3,ARRAY['광배근','이두근'],'발을 높이 올려 수평에 가깝게. 더 어렵게','wod_exercise_list',true),
('plank','플랭크','Plank','gymnastics',ARRAY[]::text[],1,ARRAY['코어','어깨','둔근'],'몸 일직선. 엉덩이 내려앉지 않게','wod_exercise_list',true),
('side-plank','사이드 플랭크','Side Plank','gymnastics',ARRAY[]::text[],2,ARRAY['복사근','코어','어깨'],'몸 옆으로 지지. 힙 들어올리기','wod_exercise_list',true),
('scaler','스케일러','Scaler','gymnastics',ARRAY[]::text[],1,ARRAY['복근','고관절굴곡근'],'상체 기대어 L포지션. 최입문 코어','wod_exercise_list',true),
('hollow-rock','홀로우 록','Hollow Rock','gymnastics',ARRAY[]::text[],2,ARRAY['복근','코어'],'팔 뻗고 다리 뻗어 바나나 자세 앞뒤 흔들기','wod_exercise_list',true),
('hollow-hold','홀로우 홀드','Hollow Hold','gymnastics',ARRAY[]::text[],2,ARRAY['복근','코어'],'홀로우 록의 정적 버전. 허리가 바닥에 닿게','wod_exercise_list',true),
('arch-rock','아치 록','Arch Rock','gymnastics',ARRAY[]::text[],2,ARRAY['척추기립근','둔근'],'엎드려 팔다리 들고 앞뒤 흔들기','wod_exercise_list',true),
('double-under','더블언더','Double Under','gymnastics',ARRAY['줄넘기'],3,ARRAY['종아리','코어','어깨'],'한 번의 점프에 줄이 두 번. 손목 작게 회전','wod_exercise_list',true),
('single-under','싱글언더','Single Under','gymnastics',ARRAY['줄넘기'],1,ARRAY['종아리'],'더블언더 대안. 3:1 또는 2:1 비율','wod_exercise_list',true),
('triple-under','트리플언더','Triple Under','gymnastics',ARRAY['줄넘기'],5,ARRAY['종아리','코어'],'한 점프에 줄 세 번. 극소수 가능','wod_exercise_list',true),
('row','로잉','Row','monostructural',ARRAY['Concept2 로잉머신'],3,ARRAY['전신','광배근','다리','코어'],'다리→코어→팔 순서. 드라이브는 다리가 70%. SPM 조절','wod_exercise_list',true),
('bike-erg','바이크 에르그','Bike Erg','monostructural',ARRAY['Concept2 바이크에르그'],3,ARRAY['대퇴사두','햄스트링','코어'],'안장 높이 조절. 케이던스와 파워 밸런스','wod_exercise_list',true),
('echo-bike','에코 바이크','Echo Bike','monostructural',ARRAY['에코바이크','어설트바이크'],4,ARRAY['전신','대퇴사두','어깨','코어'],'팔도 함께 밀고 당기기. 전신 소모. 칼로리 단위','wod_exercise_list',true),
('skierg','스키에르그','SkiErg','monostructural',ARRAY['Concept2 스키에르그'],3,ARRAY['광배근','복근','어깨','코어'],'팔로 케이블 당기며 힙 힌지. 노르딕 스키 모사','wod_exercise_list',true),
('run','달리기','Run','monostructural',ARRAY[]::text[],2,ARRAY['다리 전체','코어'],'미드풋 착지. 거리 또는 시간으로 처방','wod_exercise_list',true),
('swim','수영','Swim','monostructural',ARRAY['수영장'],3,ARRAY['전신','어깨','광배근'],'무충격 유산소. 부상자 재활에도 활용','wod_exercise_list',true),
('dumbbell-snatch','덤벨 스내치','Dumbbell Snatch','dumbbell',ARRAY['덤벨'],3,ARRAY['전신','삼각근','햄스트링'],'한손으로 머리 위 락아웃. 번갈아 또는 한손 연속','wod_exercise_list',true),
('dumbbell-clean-and-jerk','덤벨 클린 앤 저크','Dumbbell Clean & Jerk','dumbbell',ARRAY['덤벨'],3,ARRAY['전신'],'양손 또는 한손. 클린 후 저크','wod_exercise_list',true),
('dumbbell-thruster','덤벨 스러스터','Dumbbell Thruster','dumbbell',ARRAY['덤벨'],3,ARRAY['전신','대퇴사두','삼각근'],'프론트랙 스쿼트 후 프레스. 연속 동작','wod_exercise_list',true),
('dumbbell-push-press','덤벨 푸시 프레스','Dumbbell Push Press','dumbbell',ARRAY['덤벨'],2,ARRAY['삼각근','삼두근'],'딥 앤 드라이브로 보조','wod_exercise_list',true),
('dumbbell-deadlift','덤벨 데드리프트','Dumbbell Deadlift','dumbbell',ARRAY['덤벨'],2,ARRAY['햄스트링','둔근','척추기립근'],'양손 또는 한손. 척추 중립','wod_exercise_list',true),
('dumbbell-lunge','덤벨 런지','Dumbbell Lunge','dumbbell',ARRAY['덤벨'],2,ARRAY['대퇴사두','둔근'],'양손 들고 런지. 상체 직립','wod_exercise_list',true),
('dumbbell-front-squat','덤벨 프론트 스쿼트','Dumbbell Front Squat','dumbbell',ARRAY['덤벨'],2,ARRAY['대퇴사두','코어'],'덤벨 어깨에 얹어 프론트랙','wod_exercise_list',true),
('dumbbell-row','덤벨 로우','Dumbbell Row','dumbbell',ARRAY['덤벨','벤치'],2,ARRAY['광배근','이두근'],'한 손 벤치 짚고 한 손으로 당기기','wod_exercise_list',true),
('dumbbell-bench-press','덤벨 벤치 프레스','Dumbbell Bench Press','dumbbell',ARRAY['덤벨','벤치'],2,ARRAY['가슴','삼두근','삼각근'],'바벨보다 가동범위 넓음','wod_exercise_list',true),
('dumbbell-fly','덤벨 플라이','Dumbbell Fly','dumbbell',ARRAY['덤벨','벤치'],2,ARRAY['가슴'],'팔꿈치 약간 굽히고 호 그리며','wod_exercise_list',true),
('dumbbell-shoulder-press','덤벨 숄더 프레스','Dumbbell Shoulder Press','dumbbell',ARRAY['덤벨'],2,ARRAY['삼각근','삼두근'],'대칭 또는 교대. 척추 중립','wod_exercise_list',true),
('dumbbell-lateral-raise','덤벨 래터럴 레이즈','Dumbbell Lateral Raise','dumbbell',ARRAY['덤벨'],1,ARRAY['삼각근(중간)'],'팔꿈치 약간 굽히고 T자','wod_exercise_list',true),
('dumbbell-front-raise','덤벨 프론트 레이즈','Dumbbell Front Raise','dumbbell',ARRAY['덤벨'],1,ARRAY['삼각근(전면)'],'팔을 정면으로 수평까지','wod_exercise_list',true),
('dumbbell-curl','덤벨 컬','Dumbbell Curl','dumbbell',ARRAY['덤벨'],1,ARRAY['이두근'],'대칭 또는 해머 그립','wod_exercise_list',true),
('dumbbell-tricep-extension','덤벨 트라이셉 익스텐션','Dumbbell Tricep Extension','dumbbell',ARRAY['덤벨'],1,ARRAY['삼두근'],'머리 위 또는 킥백 방식','wod_exercise_list',true),
('farmer-s-carry','파머스 캐리','Farmer''s Carry','dumbbell',ARRAY['덤벨','케틀벨','바벨'],2,ARRAY['전신','코어','전완근','승모근'],'무거운 중량 들고 걷기. 척추 직립','wod_exercise_list',true),
('suitcase-carry','수트케이스 캐리','Suitcase Carry','dumbbell',ARRAY['덤벨','케틀벨'],2,ARRAY['코어','전완근','복사근'],'한손만 들고 걷기. 옆으로 기울어지지 않게','wod_exercise_list',true),
('overhead-carry','오버헤드 캐리','Overhead Carry','dumbbell',ARRAY['덤벨','케틀벨'],3,ARRAY['삼각근','코어','전완근'],'팔 완전 신전 상태로 걷기','wod_exercise_list',true),
('devil-press','데빌 프레스','Devil Press','dumbbell',ARRAY['덤벨'],4,ARRAY['전신'],'버피 후 덤벨 스내치(양손). 전신 소진','wod_exercise_list',true),
('man-maker','맨 메이커','Man Maker','dumbbell',ARRAY['덤벨'],4,ARRAY['전신'],'데드리프트→로우→푸시업→클린→스러스터 연속','wod_exercise_list',true),
('renegade-row','레니게이드 로우','Renegade Row','dumbbell',ARRAY['덤벨'],3,ARRAY['광배근','코어','어깨'],'플랭크 자세에서 교대로 당기기. 코어가 핵심','wod_exercise_list',true),
('dumbbell-step-up','덤벨 스텝업','Dumbbell Step-up','dumbbell',ARRAY['덤벨','박스'],2,ARRAY['대퇴사두','둔근'],'덤벨 들고 박스 스텝업','wod_exercise_list',true),
('dumbbell-overhead-squat','덤벨 오버헤드 스쿼트','Dumbbell Overhead Squat','dumbbell',ARRAY['덤벨'],3,ARRAY['전신','코어','삼각근'],'한손 또는 양손 오버헤드','wod_exercise_list',true),
('russian-kettlebell-swing','케틀벨 스윙 (러시안)','Russian Kettlebell Swing','kettlebell',ARRAY['케틀벨'],2,ARRAY['햄스트링','둔근','코어'],'힙 힌지. 눈높이까지. 팔은 수동적','wod_exercise_list',true),
('american-kettlebell-swing','케틀벨 스윙 (아메리칸)','American Kettlebell Swing','kettlebell',ARRAY['케틀벨'],3,ARRAY['전신','햄스트링','어깨'],'머리 위까지. CrossFit 표준. 완전 오버헤드 락아웃','wod_exercise_list',true),
('kettlebell-clean','케틀벨 클린','Kettlebell Clean','kettlebell',ARRAY['케틀벨'],3,ARRAY['전신','전완근','어깨'],'래크 포지션으로 캐치. 팔꿈치 몸통에','wod_exercise_list',true),
('kettlebell-snatch','케틀벨 스내치','Kettlebell Snatch','kettlebell',ARRAY['케틀벨'],4,ARRAY['전신','어깨','전완근'],'스윙 후 오버헤드 펀치. 손목 회전 타이밍','wod_exercise_list',true),
('kettlebell-press','케틀벨 프레스','Kettlebell Press','kettlebell',ARRAY['케틀벨'],2,ARRAY['삼각근','삼두근'],'래크에서 수직 프레스. 한손 또는 양손','wod_exercise_list',true),
('kettlebell-goblet-squat','케틀벨 고블릿 스쿼트','Kettlebell Goblet Squat','kettlebell',ARRAY['케틀벨'],2,ARRAY['대퇴사두','둔근','코어'],'가슴 앞에 케틀벨 들고 스쿼트. 엘보우로 무릎 밀기','wod_exercise_list',true),
('kettlebell-turkish-get-up','케틀벨 터키쉬 겟업','Kettlebell Turkish Get-up','kettlebell',ARRAY['케틀벨'],4,ARRAY['전신','코어','어깨'],'누운 자세→선 자세. 7단계 복합 동작. 눈은 KB에','wod_exercise_list',true),
('kettlebell-deadlift','케틀벨 데드리프트','Kettlebell Deadlift','kettlebell',ARRAY['케틀벨'],1,ARRAY['햄스트링','둔근'],'발 사이에 놓고 힙 힌지','wod_exercise_list',true),
('kettlebell-row','케틀벨 로우','Kettlebell Row','kettlebell',ARRAY['케틀벨'],2,ARRAY['광배근','이두근'],'한 손 또는 양손. 힙 힌지 후 당기기','wod_exercise_list',true),
('kettlebell-windmill','케틀벨 윈드밀','Kettlebell Windmill','kettlebell',ARRAY['케틀벨'],3,ARRAY['코어','복사근','어깨'],'오버헤드 한손, 다른 손 발 쪽으로. 회전 유연성','wod_exercise_list',true),
('kettlebell-halo','케틀벨 할로','Kettlebell Halo','kettlebell',ARRAY['케틀벨'],2,ARRAY['어깨','코어','삼두근'],'머리 주위로 원 그리기. 어깨 워밍업','wod_exercise_list',true),
('kettlebell-hot-potato','케틀벨 핫 포테이토','Kettlebell Hot Potato','kettlebell',ARRAY['케틀벨'],1,ARRAY['어깨','전완근'],'양손 교대로 패스. 워밍업 또는 보조운동','wod_exercise_list',true),
('kettlebell-swing-to-squat','케틀벨 스윙 투 스쿼트','Kettlebell Swing to Squat','kettlebell',ARRAY['케틀벨'],3,ARRAY['전신'],'스윙 후 스쿼트 캐치. 연속 복합 동작','wod_exercise_list',true),
('kettlebell-farmer-s-carry','케틀벨 파머스 캐리','Kettlebell Farmer''s Carry','kettlebell',ARRAY['케틀벨'],2,ARRAY['전신','코어','전완근'],'양손 또는 한손. 거리 기반 처방','wod_exercise_list',true),
('wall-ball','월볼','Wall Ball','medball',ARRAY['메드볼','벽'],2,ARRAY['대퇴사두','삼각근','코어'],'스쿼트 후 볼 던져 타겟 맞히기. 표준 10ft/9ft','wod_exercise_list',true),
('med-ball-clean','메드볼 클린','Med Ball Clean','medball',ARRAY['메드볼'],3,ARRAY['전신'],'메드볼로 클린 동작 모사. 초보자 역도 입문','wod_exercise_list',true),
('med-ball-slam','메드볼 슬램','Med Ball Slam','medball',ARRAY['메드볼'],2,ARRAY['코어','광배근','어깨'],'머리 위로 올려 바닥에 힘껏 던지기','wod_exercise_list',true),
('slam-ball','슬램볼','Slam Ball','medball',ARRAY['슬램볼'],3,ARRAY['전신','코어','어깨'],'튕기지 않는 볼. 더 강하게 내리찍기','wod_exercise_list',true),
('med-ball-russian-twist','메드볼 트위스트','Med Ball Russian Twist','medball',ARRAY['메드볼'],2,ARRAY['복사근','코어'],'앉아서 좌우로 볼 이동','wod_exercise_list',true),
('med-ball-overhead-lunge','메드볼 오버헤드 런지','Med Ball Overhead Lunge','medball',ARRAY['메드볼'],3,ARRAY['전신','코어','어깨'],'볼 오버헤드로 들고 런지','wod_exercise_list',true),
('med-ball-pass','메드볼 패스','Med Ball Pass','medball',ARRAY['메드볼'],2,ARRAY['전신','코어'],'파트너와 주고받기. 다양한 각도','wod_exercise_list',true),
('med-ball-box-jump','메드볼 박스 점프','Med Ball Box Jump','medball',ARRAY['메드볼','박스'],3,ARRAY['다리','코어'],'볼 들고 박스 점프. 밸런스 주의','wod_exercise_list',true),
('med-ball-bear-crawl','메드볼 베어 크롤','Med Ball Bear Crawl','medball',ARRAY['메드볼'],3,ARRAY['전신','코어','어깨'],'볼 굴리며 베어 크롤. 코어 안정성','wod_exercise_list',true),
('sandbag-clean','샌드백 클린','Sandbag Clean','other_equipment',ARRAY['샌드백'],3,ARRAY['전신'],'불규칙한 무게로 안정성 추가 도전','wod_exercise_list',true),
('sandbag-carry','샌드백 캐리','Sandbag Carry','other_equipment',ARRAY['샌드백'],2,ARRAY['전신','코어'],'어깨 또는 베어허그. 거리 처방','wod_exercise_list',true),
('sandbag-over-shoulder','샌드백 오버 숄더','Sandbag Over Shoulder','other_equipment',ARRAY['샌드백'],3,ARRAY['전신','둔근','코어'],'들어 어깨 너머로 던지기','wod_exercise_list',true),
('sled-push','슬레드 푸시','Sled Push','other_equipment',ARRAY['슬레드'],3,ARRAY['대퇴사두','둔근','코어'],'낮은 자세로 힘껏 밀기. 경기력 훈련','wod_exercise_list',true),
('sled-pull','슬레드 풀','Sled Pull','other_equipment',ARRAY['슬레드','로프','스트랩'],3,ARRAY['햄스트링','광배근','코어'],'뒤로 당기기. 다양한 자세','wod_exercise_list',true),
('tire-flip','타이어 플립','Tire Flip','other_equipment',ARRAY['타이어'],4,ARRAY['전신','둔근','허리'],'데드리프트→프레스→플립. 허리 부상 주의','wod_exercise_list',true),
('battle-rope-wave','배틀로프 웨이브','Battle Rope Wave','other_equipment',ARRAY['배틀로프'],2,ARRAY['어깨','코어','전완근'],'양손 또는 교대 웨이브. 시간 처방','wod_exercise_list',true),
('battle-rope-slam','배틀로프 슬램','Battle Rope Slam','other_equipment',ARRAY['배틀로프'],3,ARRAY['어깨','코어','광배근'],'양손으로 위아래 내리치기','wod_exercise_list',true),
('pallof-press','팰로프 프레스','Pallof Press','other_equipment',ARRAY['케이블','밴드'],2,ARRAY['코어','복사근'],'몸 옆면으로 저항. 앤티-로테이션','wod_exercise_list',true),
('atlas-stone','아틀라스 스톤','Atlas Stone','other_equipment',ARRAY['아틀라스스톤'],5,ARRAY['전신'],'둥근 돌 들어 플랫폼 위로. 스트롱맨','wod_exercise_list',true),
('keg-carry','케그 캐리','Keg Carry','other_equipment',ARRAY['케그'],3,ARRAY['전신','코어'],'물 또는 모래 채운 통 들고 이동','wod_exercise_list',true),
('box-dip','박스 딥','Box Dip','other_equipment',ARRAY['박스','벤치'],2,ARRAY['삼두근','어깨'],'박스에 손 대고 딥. 링/바 대안','wod_exercise_list',true),
('bear-crawl','베어 크롤','Bear Crawl','accessory',ARRAY[]::text[],2,ARRAY['전신','코어','어깨'],'무릎 살짝 들고 기어가기. 전신 조율','wod_exercise_list',true),
('crab-walk','크랩 워크','Crab Walk','accessory',ARRAY[]::text[],2,ARRAY['삼두근','코어','둔근'],'등 보며 이동. 어깨 열기','wod_exercise_list',true),
('superman','슈퍼맨','Superman','accessory',ARRAY[]::text[],1,ARRAY['척추기립근','둔근'],'엎드려 팔다리 동시에 올리기','wod_exercise_list',true),
('squat-jump','스쿠어트 점프','Squat Jump','accessory',ARRAY[]::text[],2,ARRAY['대퇴사두','둔근'],'스쿼트 후 점프. 파워 발달','wod_exercise_list',true),
('split-squat-jump','스플릿 스쿼트 점프','Split Squat Jump','accessory',ARRAY[]::text[],3,ARRAY['대퇴사두','둔근'],'런지 자세에서 점프 후 다리 교체','wod_exercise_list',true),
('cossack-squat','코삭 스쿼트','Cossack Squat','accessory',ARRAY[]::text[],3,ARRAY['내전근','둔근','대퇴사두'],'좌우 교대 측면 스쿼트. 유연성','wod_exercise_list',true),
('glute-bridge','글루트 브릿지','Glute Bridge','accessory',ARRAY['바벨'],1,ARRAY['둔근','햄스트링'],'누워 힙 들기. 상단에서 짜기','wod_exercise_list',true),
('hip-thrust','힙 쓰러스트','Hip Thrust','accessory',ARRAY['벤치','바벨'],2,ARRAY['둔근','햄스트링'],'어깨를 벤치에 대고 무거운 중량. 최고 둔근 운동','wod_exercise_list',true),
('single-leg-glute-bridge','싱글 레그 글루트 브릿지','Single Leg Glute Bridge','accessory',ARRAY[]::text[],2,ARRAY['둔근','햄스트링'],'한다리로 힙 들기. 좌우 비대칭 교정','wod_exercise_list',true),
('wall-sit','월 싯','Wall Sit','accessory',ARRAY[]::text[],2,ARRAY['대퇴사두'],'벽에 기대어 90도 앉기. 시간 처방','wod_exercise_list',true),
('calf-raise','칼프 레이즈','Calf Raise','accessory',ARRAY['덤벨'],1,ARRAY['비복근','가자미근'],'발뒤꿈치 올리기. 단면 또는 양면','wod_exercise_list',true),
('reverse-hyper','리버스 하이퍼','Reverse Hyper','accessory',ARRAY['리버스하이퍼머신'],2,ARRAY['둔근','척추기립근','햄스트링'],'골반 거꾸로 올리기. 허리 재활','wod_exercise_list',true),
('ring-face-pull','링 페이스풀','Ring Face Pull','accessory',ARRAY['링'],2,ARRAY['삼각근(후면)','외회전근'],'링을 얼굴로 당기기. 어깨 건강','wod_exercise_list',true),
('band-pull-apart','밴드 풀어파트','Band Pull-apart','accessory',ARRAY['밴드'],1,ARRAY['삼각근(후면)','승모근(중간)'],'가슴 앞에서 밴드 양옆으로 당기기','wod_exercise_list',true),
('band-monster-walk','밴드 몬스터 워크','Band Monster Walk','accessory',ARRAY['밴드'],2,ARRAY['둔근(중간)','외전근'],'발목 밴드하고 게걸음. 臀근 활성화','wod_exercise_list',true),
('wrist-curl','팜 다운 리스트 컬','Wrist Curl','accessory',ARRAY['덤벨','바벨'],1,ARRAY['전완굴근'],'손목 굽히기. 그립 강화','wod_exercise_list',true),
('dead-hang','행잉 그립','Dead Hang','accessory',ARRAY['풀업바'],1,ARRAY['전완근','광배근','어깨'],'매달리기만 함. 그립과 어깨 건강','wod_exercise_list',true),
('scapular-pull-down','스캡 풀다운','Scapular Pull-down','accessory',ARRAY['풀업바'],1,ARRAY['하부승모근','전거근'],'팔 펴고 견갑골만 내리기. 어깨 안정성','wod_exercise_list',true),
('leg-raise','레그 레이즈','Leg Raise','accessory',ARRAY[]::text[],2,ARRAY['복근','고관절굴곡근'],'누워 다리 90도로 올리기','wod_exercise_list',true),
('v-up','브이업','V-up','accessory',ARRAY[]::text[],3,ARRAY['복근','고관절굴곡근'],'팔다리 동시에 만나기. 풀 가동범위','wod_exercise_list',true),
('mountain-climber','마운틴 클라이머','Mountain Climber','accessory',ARRAY[]::text[],2,ARRAY['코어','고관절굴곡근','어깨'],'플랭크에서 무릎 가슴으로 교대 당기기','wod_exercise_list',true),
('spiderman-plank','스파이더맨 플랭크','Spiderman Plank','accessory',ARRAY[]::text[],3,ARRAY['코어','복사근','어깨'],'플랭크에서 무릎을 팔꿈치로','wod_exercise_list',true),
('inchworm','인치웜','Inchworm','accessory',ARRAY[]::text[],2,ARRAY['전신','햄스트링','어깨'],'손으로 걸어나가 푸시업 후 복귀. 워밍업','wod_exercise_list',true),
('high-knees','하이 니','High Knees','accessory',ARRAY[]::text[],1,ARRAY['고관절굴곡근','코어'],'제자리 달리기 무릎 높이 올리기','wod_exercise_list',true),
('butt-kicks','버트 킥','Butt Kicks','accessory',ARRAY[]::text[],1,ARRAY['햄스트링'],'달리기 중 발뒤꿈치 둔근으로','wod_exercise_list',true),
('side-shuffle','사이드 셔플','Side Shuffle','accessory',ARRAY[]::text[],1,ARRAY['둔근(중간)','내전근'],'옆으로 게걸음. 민첩성','wod_exercise_list',true),
('lateral-bound','래터럴 바운드','Lateral Bound','accessory',ARRAY[]::text[],2,ARRAY['둔근','대퇴사두','종아리'],'옆으로 한발 점프. 파워와 밸런스','wod_exercise_list',true),
('box-step-over','박스 스텝오버','Box Step-over','accessory',ARRAY['박스'],1,ARRAY['대퇴사두','둔근'],'박스를 한발씩 넘어 이동','wod_exercise_list',true),
('plate-lunge','플레이트 런지','Plate Lunge','accessory',ARRAY['원판'],2,ARRAY['대퇴사두','둔근','어깨'],'원판 오버헤드로 들고 런지','wod_exercise_list',true),
('bench-dip','트라이셉 딥 (벤치)','Bench Dip','accessory',ARRAY['벤치'],1,ARRAY['삼두근'],'등지고 벤치에 손 짚고 딥','wod_exercise_list',true),
('ab-wheel-rollout','스파인 롤아웃','Ab Wheel Rollout','accessory',ARRAY['AB휠'],4,ARRAY['복근','광배근','코어'],'무릎 또는 선 자세. 허리 꺾이지 않게','wod_exercise_list',true)
ON CONFLICT (slug) DO NOTHING;
