name: Deploy to Cafe24

on:
  push:
    branches:
      - main
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: 'CAFE24'
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, gd, xml, dom, json, mysql, curl
          tools: composer:v2

      - name: 📦 Install Dependencies
        run: composer install --no-dev --optimize-autoloader


      - name: 📦 Archive Release
        run: zip -r release.zip . -x "*.git*" ".github/*" "tests/*" "writable/cache/*" "writable/logs/*" "writable/session/*" ".gitignore" "README.md" "composer.lock" "tools/*"

      - name: 🚀 Upload Artifact
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "release.zip"
          target: "www/"

      - name: ♻️ Extract & Migrate
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd www/
            unzip -o release.zip
            rm release.zip
            # Permissions Fix (Ignore errors)
            chmod -R 755 tools || true
            # Fix PHP library path (MySQL client error)
            export LD_LIBRARY_PATH=/usr/local/mysql/lib:$LD_LIBRARY_PATH
            php -v
            # CI4 Migration Execution (Auto-confirm)
            echo "y" | php spark migrate --all
            # Cache Clear
            php spark cache:clear
